#ifndef __CMD_TYPES_H
#define  __CMD_TYPES_H
// msg's sent from client to TS-7200
#warning "including cmd_types"
static enum cmd_types
{
	NON_CMD,
	DESK_LIGHT,
	EAST_LIGHT,
	NORTHWEST_LIGHT,
	SOUTHEAST_LIGHT,
	MIDDLE_LIGHT,
	WEST_LIGHT,
	NORTHEAST_LIGHT,
	SOUTHWEST_LIGHT,	// last one for garage (146)
	WATER_HEATER,		// first one for garage2 (146)
	WATER_VALVE1,
	WATER_VALVE2,
	WATER_VALVE3,
	WATER_PUMP,			// last one for 146
	CHICK_LIGHT,		// start of 147
	CHICK_HEATER,
	BENCH_12V_1,
	BENCH_12V_2,
	BENCH_5V_1,
	BENCH_5V_2,
	BENCH_3V3_1,
	BENCH_3V3_2,
	BENCH_LIGHT1,
	BENCH_LIGHT2,
	BATTERY_HEATER,		// last one for 147
	CABIN_SOUTH,		// start of 154
	CABIN_FILECB,
	CABIN3,
	CABIN_KITCHEN,
	CABIN_DOOR,
	CABIN_EAST,
	CABIN7,
	CABIN8,				// last one for 154
	COOP1_LIGHT,		// start of 151
	COOP1_HEATER,
	COOP2_LIGHT,
	COOP2_HEATER,
	OUTDOOR_LIGHT1,
	OUTDOOR_LIGHT2,
	UNUSED150_1,
	UNUSED150_2,
	UNUSED150_3,
	UNUSED150_4,
	UNUSED150_5,
	UNUSED150_6,
	UNUSED150_7,
	UNUSED150_8,
	UNUSED150_9,
	UNUSED150_10,
	GET_TEMP4,
	SHUTDOWN_IOBOX,
	REBOOT_IOBOX,
	SET_TIME,
	GET_TIME,
	DISCONNECT,
	DISCONNECT_ALL,
	SEND_TIMEUP,
	UPTIME_MSG,
	SEND_STATUS,
	SEND_CLIENT_LIST,
	SHELL_AND_RENAME,
	EXIT_TO_SHELL,
	UPDATE_STATUS,
	SEND_MESSAGE,
	SET_VALID_DS,
	SET_DS_INTERVAL,
	DLLIST_SHOW,
	DLLIST_SAVE,
	DS1620_MSG,
	TURN_ALL_LIGHTS_OFF,
	SET_PROPERTIES,
	SEND_MESSAGE2,
	SET_CLIENT_NAME,
	SEND_IOT_VALUES,
	SEND_IOT_CMD
}CMD_TYPES;

#endif